enhancement: changed workflow so that deployment only happens when changes are made to the backend.

diff --git a/.github/workflows/docker_build_push.yml b/.github/workflows/docker_build_push.yml
--- a/.github/workflows/docker_build_push.yml
+++ b/.github/workflows/docker_build_push.yml
@@ -19,22 +19,35 @@ jobs:
     - name: Login to DockerHub
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-    - name: Build and push Docker image
-      run: |
-        cd backend
-        docker build -t "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest" .
-        docker push "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
+    - name: Generate Checksum of Backend Code
+      run: sha256sum backend/* > code_checksum.txt
 
-    - name: Deploy to EC2
+    - name: Compare Checksums and Build if Different
       run: |
-        set +x
-        echo "${{ secrets.PEM }}" > key.pem 
-        set -x
-        chmod 600 key.pem
-        ssh -i ./"key.pem" -o StrictHostKeyChecking=no -o ec2-user@${{ secrets.CLOUD_URL }} <<EOF
-          docker stop haeng
-          docker rm haeng
-          docker rmi "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
-          docker pull "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
-          docker run -d --name haeng -p 8080:8000 --env-file haengsha-env/.env "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
-        EOF
+        # try to retrieve checksum from latest Docker image
+        docker pull "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
+        if docker run --rm "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest" cat /app_checksum.txt > container_checksum.txt; then
+          echo "Checksum file retrieved successfully."
+        else
+          echo "Checksum file not found in Docker image. Create an empty file."
+          touch code_checksum.txt
+
+        if ! cmp -s code_checksum.txt container_checksum.txt; then
+          echo "Checksums do not match, proceed with build and pull."
+          cd backend
+            docker build -t "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest" .
+            docker push "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
+            set +x
+            echo "${{ secrets.PEM }}" > key.pem 
+            set -x
+            chmod 600 key.pem
+            ssh -i ./"key.pem" -o StrictHostKeyChecking=no ec2-user@${{ secrets.CLOUD_URL }} <<EOF
+              docker stop haeng
+              docker rm haeng
+              docker rmi "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
+              docker pull "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
+              docker run -d --name haeng -p 8080:8000 --env-file haengsha-env/.env "${{ secrets.DOCKER_USERNAME }}/haengsha-backend:latest"
+            EOF      
+        else
+          echo "Checksums match, no need to build."
+
